-- Admin content helpers for ekbkyrgyzdar
-- Writes to carusel / recommendations go through Edge Function admin-content
-- (service role + BROADCAST_ADMIN_KEY). Clients only need SELECT.

-- Carousel table (already exists in prod; idempotent)
CREATE TABLE IF NOT EXISTS public.carusel (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  images text,
  links text
);

ALTER TABLE public.carusel ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "carusel_select_all" ON public.carusel;
CREATE POLICY "carusel_select_all"
  ON public.carusel
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- No INSERT/UPDATE/DELETE policies for anon/authenticated.
-- Mutations: supabase/functions/admin-content (service role).

-- Recommendations: SELECT already in recommendations.sql.
-- Mutations: same admin-content edge function.
